instagram/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :posts, only: [:new, :create, :show, :destroy]

  resources :comments, only: [:create, :destroy]

  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  
  resources :users do
    resources :follows, only: [:create, :destroy]
  end

  delete 'posts/:id', to: 'posts#destroy', as: 'destroy_post'

  get 'show/:user_name', to: 'posts#show', as: 'profile'

  get 'show/:user_name/followings', to: 'follows#show', as: 'user_followings'

  # homepage for signed in users
  get 'homepage', to: 'public#homepage'

  # Defines the root path route ("/")
  devise_scope :user do
    root 'users/sessions#new'
  end
end

instagram/app/views/layouts/_header.html.erb
<%= stylesheet_link_tag "header" %>

<% if user_signed_in? %>
<header id="main-header">
    <div class="instagram-logo">
        <%= link_to image_tag("instagram-text-icon.png", height: 30, class:"instagram-text-icon"), homepage_path  %>
    </div>

    <div class="search-bar">
        <div>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="search-icon-container" viewBox="0 0 16 16">
            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
            </svg>
        </div>
        <input class="searchbar" type="text" class="searchbar-input" placeholder="Search...">
    </div>

    <div class="nav-item-3">
      <ul class="nav-items">
        <li class="navbar-item">
        <%= link_to homepage_path do %>
        <span class="home-navicon">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
            </svg>
        </span>
        <% end %>
        </li>
        <li class="navbar-item">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
            <path d="M0 7.76C0 3.301 3.493 0 8 0s8 3.301 8 7.76-3.493 7.76-8 7.76c-.81 0-1.586-.107-2.316-.307a.639.639 0 0 0-.427.03l-1.588.702a.64.64 0 0 1-.898-.566l-.044-1.423a.639.639 0 0 0-.215-.456C.956 12.108 0 10.092 0 7.76zm5.546-1.459-2.35 3.728c-.225.358.214.761.551.506l2.525-1.916a.48.48 0 0 1 .578-.002l1.869 1.402a1.2 1.2 0 0 0 1.735-.32l2.35-3.728c.226-.358-.214-.761-.551-.506L9.728 7.381a.48.48 0 0 1-.578.002L7.281 5.98a1.2 1.2 0 0 0-1.735.32z"/>
        </svg>
        </li>
        <li class="navbar-button new-post-button">
            <%= link_to "+", new_post_path, class:"btn btn-light" %>
        </li>
        <li class="navbar-item">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
            <path d="M8 16.016a7.5 7.5 0 0 0 1.962-14.74A1 1 0 0 0 9 0H7a1 1 0 0 0-.962 1.276A7.5 7.5 0 0 0 8 16.016zm6.5-7.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0z"/>
            <path d="m6.94 7.44 4.95-2.83-2.83 4.95-4.949 2.83 2.828-4.95z"/>
            </svg>
        </li>
        <li class="navbar-item">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
            <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
        </svg>
        </li>
        <li class="navbar-item">
            <% if current_user.profile_image.url %>
                <%= link_to image_tag(current_user.profile_image.url, height: 35, class:"my-img"), profile_path(current_user.user_name)  %>
            <% else %>
                <%= link_to image_tag('default_profile_photo.png', height: 35, class:"my-img"), profile_path(current_user.user_name) %>
            <% end %>
        </li>
      </ul>
      <div class="navbar-buttons">
        <p class="navbar-button sign-out-nav-button">
            <%= link_to "Sign out", destroy_user_session_path, data: {turbo_method: :delete}, class:"btn btn-light" %>
        </p>
      </div>
    </div>
</header>
<% end %>

instagram/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Instagram</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <% if notice %> <p class="alert alert-success"><%= notice %></p> <% end %>
  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </body>
</html>