instagram/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :posts, only: [:new, :create, :show, :destroy]

  resources :comments, only: [:create, :destroy]

  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  
  resources :users do
    resources :follows, only: [:create, :destroy]
  end

  delete 'posts/:id', to: 'posts#destroy', as: 'destroy_post'

  get 'show/:user_name', to: 'posts#show', as: 'profile'

  get 'show/:user_name/followings', to: 'follows#show', as: 'user_followings'

  # homepage for signed in users
  get 'homepage', to: 'public#homepage'

  # Defines the root path route ("/")
  devise_scope :user do
    root 'users/sessions#new'
  end
end

instagram/app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :media, MediaUploader
    validates :media, presence: true

    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
end

instagram/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:update, :destroy, :show, :new, :create]
    before_action :set_post, only: [:update, :destroy]

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(post_params)
         
        @post.user = current_user

        if @post.save
            redirect_to homepage_path, notice: "Post created Successfully"
        else
            redirect_to new_post_path, notice: "Post couldn't be saved"
        end

    end
     
    def show
        @user = User.find_by_user_name(params[:user_name])
        @posts = Post.all.order(created_at: :desc)
        @comment = Comment.new
        @post_count = @user.posts.count
    end

    def update
    end

    def destroy
        if @post.user == current_user
            if @post.destroy
                redirect_to profile_path(current_user.user_name)
            end
        end
    end

    private

    def post_params
        params.require(:post).permit(:media, :caption, :location)
    end

    def set_post
        @post = Post.find(params[:id])
    end

end

instagram/app/views/posts/_comments.html.erb
<% post.comments.where(parent_id: nil).order(created_at: :desc).each do |comment| %>

<div class="existing-comment-container">

    <div class="existing-comment">
        <%= link_to profile_path(comment.user.user_name) do %>
            <strong><%= comment.user.user_name %></strong>
        <% end %>
        <span class="existing-comment-content">
            <%= comment.comment_text %>
        </span>
        <span class="existing-comment-delete-button">
        </span>
        <% if comment.user == current_user %>
            <%= link_to "Delete", comment_path(comment), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"comment-delete" %>
        <% end %>
    </div>
    <br />
    <span class="comment-time-ago">
        <%= time_ago_in_words comment.created_at %>
    </span>

    <a href="#" class="sub-comment-form-display-button">Reply</a>

    <div class="sub-comment-form">
        <%= form_for Comment.new do |f| %>
            <%= f.hidden_field :post_id, value: post.id %>
            <%= f.hidden_field :parent_id, value: comment.id %>
            <%= f.text_field :comment_text, class:"sub-comment-text-box", placeholder:"Add a comment..." %>
            <%= f.submit "Post", class:"sub-commment-post-button" %>
        <% end %>
    </div>

    <% comment.comments.order(created_at: :desc).each do |cmmnt| %>
        <div class="sub-comments">
            <%= link_to profile_path(cmmnt.user.user_name) do %>
                <%= cmmnt.user.user_name %>
            <% end %>
            <%= cmmnt.comment_text %>
            <% if cmmnt.user == current_user %>
                <%= link_to "Delete", comment_path(cmmnt), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"sub-comment-delete" %>
            <% end %>
            <br />
            <span class="sub-comments-time-ago">
                <%= time_ago_in_words cmmnt.created_at %>
            </span>
        </div>
    <% end %>
</div>

<% end %> 

<script>
    replyTags = document.querySelectorAll(".sub-comment-form-display-button");  // to get all 'Reply' action tags
    replyTags.forEach( (replyTag) => {
        replyTag.addEventListener('click', (showSubcommentForm) => {
            showSubcommentForm.preventDefault();
            replyTag.nextElementSibling.style = "display: block;";
        })
    })
</script>

instagram/app/views/posts/_errors.html.erb
<% if post.errors.any? %>
    <ul class="list-group">
        <% post.errors.full_messages.each do |message| %>
            <li class="list-group-item list-group-item-danger"> <%= messsage %> </li>
        <% end %>
    </ul>
<% end %>

instagram/app/views/posts/_form.html.erb
<div class="new-post-page-container">
<%= form_for @post do |f| %>
    <div class="new-post-container">
        <div class="new-post-item">
            <%= f.file_field :media %>
        </div>

        <div class="new-post-item">
            <%= f.label :caption %><br />
            <%= f.text_field :caption, class:"new-post-text-fields" %>
        <div class="new-post-item">

        <div class="new-post-item">
            <%= f.label :location %><br />
            <%= f.text_field :location, class:"new-post-text-fields" %>
        </div>
        
        <%= f.submit "Save Post", class:"btn btn-dark" %>
    </div>
<% end %> 
</div>
<%= render 'errors', post: @post %>

instagram/app/views/posts/new.html.erb
<%= render "posts/form" %>

instagram/app/views/posts/show.html.erb
<section class="user-posts-container">

  <div class="profile-page-header">
    <% if @user.profile_image.url %>
        <%= image_tag @user.profile_image.url, class:"profile-image" %>
    <% else %>
        <%= image_tag 'default_profile_photo.png', class:"profile-image default-profile-image" %>
    <% end %>

    <div class="profile-details">

        <div class="header-username">
            <%= @user.user_name %>
        </div>
        <br />
        <% if @user == current_user %>
            <%= link_to 'Edit Profile', edit_user_registration_path, data: { turbo_method: :get }, class:"btn btn-dark" %>
        <% else %>
            <% is_followed = @user.followers.find { |follower| follower.id == current_user.id} %>
            
            <% if is_followed %>
                <%= button_to 'Unfollow', user_follow_path(@user, current_user), method: :delete, class:"btn btn-dark follow-unfollow-button" %>
            <% else %>
                <%= button_to 'Follow', user_follows_path(@user), method: :post, class:"btn btn-dark follow-unfollow-button" %>
            <% end %>
        <% end %>

        <div class="header-profile-stats">
            <span class="header-profile-stat"><%= pluralize @post_count, "post" %></span>
            <span class="header-profile-stat"><b><%= @user.followers.count %></b> followers</span>
            <span class="header-profile-stat"><b><%= @user.followings.count %></b> following</span>
        </div>

        <br />
        <%= link_to 'Followings', user_followings_path(@user.user_name), data: { turbo_method: :get }, class:"btn btn-dark" %>
        
        <div class="header-user-fullname">
            <%= "#{@user.first_name} #{@user.last_name}" %>
        </div>

        <div class="header-user-bio">
            <%= @user.bio %>
        </div>
    </div>
  </div>

  <div class="profile-page-separator-line"></div>

  <span><b>POSTS</b></span>

  <div class="profile-posts-container">

    <% @posts.each do |p| %>
        
        <% if p.user == @user %>
            <article>

                <% media_extension_name = p.media.url.to_s.downcase.split('.')[-1] %>
                <% if %w(jpg jpeg gif png).include? media_extension_name %>
                    <%= image_tag p.media.url, class:"post-card-media"  %>
                <% elsif %w(mkv mp4 mov avi).include? media_extension_name %>
                    <%= video_tag url_for(p.media.url), class:"post-card-media", controls: true %>
                <% end %>

                <span class="post-card-header-location">
                    <%= p.location %>
                </span>

                <% if p.user == current_user %>
                    <%= link_to "Delete Post", destroy_post_path(p), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:"comment-delete post-delete" %>
                <% end %>

                <div>
                    <span class="post-card-caption profile-page-post-card-caption"><%= p.caption %></span>
                </div>

                <span class="post-card-time-duration"><%= "#{(time_ago_in_words p.created_at).to_s.upcase} AGO" %></span>

                <%= render "posts/comments", post: p %>

                <span class="post-card-dividing-line"></span>

                <div class="post-card-comment">
                    <%= form_for @comment do |f| %>
                        <%= f.hidden_field :post_id, value: p.id %>
                        <%= f.text_field :comment_text, class:"post-card-comment-box", placeholder:"Add a comment..." %>
                        <%= f.submit "Post", class:"post-button" %>
                    <% end %>
                </div>

            </article>
        <% end %>

    <% end %>
  </div>
</section>